server:
    port: 9130
spring:
  datasource:
    url: jdbc:mysql://192.168.100.245:3307/andun_doctor?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: java_shouxing        #root   java_shouxing
    password: oVjR_gGlkNuAkeA5  #Andun.2016.!  oVjR_gGlkNuAkeA5
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: info-module

eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:9670/eureka/

mapper:
  identity: MYSQL
  not-empty: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.doctor.info_module.mappper: debug